Add topic editor
haroohie-club/SerialLoops pull request #30
Opened 2023-02-13 00:26 UTC by jonko0493

Adds topic items and a topic editor. Also adds references to topics and scripts accordingly.

![image](https://user-images.githubusercontent.com/69772986/218346459-b8050ddc-178d-4549-8ac8-c1dea0c7faaf.png)

Doesn't look amazing but is functional.

2023-02-13 01:30 UTC, WiIIiam278 approved these changes
Most excellent :)

2023-02-13 01:30 UTC, WiIIiam278 commented on src/SerialLoops/Editors/TopicEditor.cs
> +                shortsLayout.Items.Add(ControlGenerator.GetControlWithLabel($"Short {i}", new TextBox() { Text = _topic.Topic.UnknownShorts[i].ToString() }));
Do we know what these do yet out of interest?

2023-02-13 01:30 UTC, WiIIiam278 commented on src/SerialLoops/Editors/TopicEditor.cs
> +                ControlGenerator.GetControlWithLabel("Associated Script", linkedScriptDropDown),
Could we perhaps do an iconified blue file link via the ControlGenerator next to the dropdown?
Given how many scripts there are we should probably make this a filterable selection modal in the future

2023-02-13 01:35 UTC, WiIIiam278 commented on src/SerialLoops.Lib/Items/TopicItem.cs
> +        public TopicItem(TopicStruct topicStruct, Project project) : base($"{topicStruct.Id} {topicStruct.Title}", ItemType.Topic)
Just a thought -- this makes the item name modifiable, which probably isn't a problem as the fact there's a proceeding ID still makes them unique, but may be a bit confusing and cause issues at some point when users expect certain things of item names.
Perhaps we may want to consider some sort of "item display name" separate from the actual item "id" we're assigning each one?

2023-02-13 01:35 UTC, jonko0493 commented on src/SerialLoops/Editors/TopicEditor.cs
> +                shortsLayout.Items.Add(ControlGenerator.GetControlWithLabel($"Short {i}", new TextBox() { Text = _topic.Topic.UnknownShorts[i].ToString() }));
No :") I'm gonna work on it at some point but they're pretty confusing and a bit low priority at the moment.

2023-02-13 01:36 UTC, jonko0493 commented on src/SerialLoops.Lib/Items/TopicItem.cs
> +        public TopicItem(TopicStruct topicStruct, Project project) : base($"{topicStruct.Id} {topicStruct.Title}", ItemType.Topic)
Oh you're right. I actually did introduce an item display name for this purpose; I'll see if I can use that.

2023-02-13 01:36 UTC, jonko0493 commented on src/SerialLoops/Editors/TopicEditor.cs
> +                ControlGenerator.GetControlWithLabel("Associated Script", linkedScriptDropDown),
Yes, I will add this! And agreed, we're going to want filterable modals at some points.

2023-02-13 15:13 UTC, WiIIiam278 reviewed
Could we perhaps update the topic links in the PuzzleEditor to be item links instead of the placeholder links with the topic ID text, too?

2023-02-14 15:12 UTC, WiIIiam278 requested changes
Just a fix needed for item selection context menus as a result of the DisplayName change

2023-02-14 15:12 UTC, WiIIiam278 commented on src/SerialLoops/Editors/PuzzleEditor.cs
> +            StackLayout topics = new() { Orientation = Orientation.Vertical, Spacing = 5 };
This change seems to cause the GroupBox name to not display properly on mac as the name is too long for the now thinner box

![image](https://user-images.githubusercontent.com/31187453/218776734-d7d16a78-482b-419b-8c94-1f238e927001.png)

2023-02-14 15:12 UTC, WiIIiam278 commented on src/SerialLoops.Lib/Items/ItemDescription.cs
> +        public string DisplayName { get; protected set; }
We might want to have Search use DisplayName instead of name to show suggestions for topic names as right now it's just using Name

2023-02-14 16:59 UTC, jonko0493 commented on src/SerialLoops.Lib/Items/ItemDescription.cs
> +        public string DisplayName { get; protected set; }
Done!

2023-02-14 17:10 UTC, jonko0493 commented on src/SerialLoops/Controls/ItemExplorerPanel.cs
> +                ItemDescription item = _project.FindItem(view.SelectedItem?.Text.Split(" - ")[0]);
Refactored this into `FindItem`. As for ID - Nice name -- we'll do that through the current system of Name/DisplayName and not have any breakage. :)

2023-02-14 19:24 UTC, merged