New icons for camera origin and pathing, new buttons for adding/removing commands/sections in scripts
haroohie-club/SerialLoops pull request #50
Opened 2023-03-23 19:25 UTC by WiIIiam278

2023-03-24 05:25 UTC, jonko0493 requested changes
The look and feel is fantastic -- just a couple of changes to fix some nullrefs needed!

2023-03-24 05:25 UTC, jonko0493 commented on src/SerialLoops/Editors/ScriptEditor.cs
> +                            Index = section.Command.Index + 1,
This will fail if a section is selected instead of a command

2023-03-24 18:44 UTC, WiIIiam278 commented on src/SerialLoops.Lib/Script/ScriptItemCommand.cs
> +        public static List<ScriptParameter> GetBlankParameters(CommandVerb verb, Project project, EventFile eventFile)
yeah neither do I for the reason you outlined -- reason I did this was because I sort of assumed if I passed a bunch of zeroed shorts as parameters to that it'd probably crash as certain arguments can't be zero -- but maybe I was wrong there.

2023-03-26 08:07 UTC, jonko0493 approved these changes
Ofc you should push part 2 changes up before merging, but part 1 addresses my core concerns so approving to unblock you!

2023-03-28 00:51 UTC, merged